# Assignment 8

In [17]:
import numpy as np
import random
a = np.random.rand(4,2)
b = np.full((4,2),5)
print(a)
print('\n')
print(b)

[[0.60436448 0.53876218]
 [0.72833009 0.53703768]
 [0.14391081 0.55566363]
 [0.80008465 0.27112378]]


[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [33]:
import numpy as np
a = np.zeros((3,5))
print(a)
print(a.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


In [31]:
import numpy as np
a = np.ones(((4,3,2)))
print(a)
print(a.dtype)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
float64


Q2. write a numpy program to create a 3x3 2D matrix with values ranging from 2 to 10.

In [37]:
import numpy as np
a = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix with values from 2 to 10:")
print(a)

3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [43]:
import pandas as pd
vec = np.zeros(10)
print("before updation: \n",vec)
# Update the 6th value (index 5) to 11
vec[5] = 11
print("after updation: \n",vec)

before updation: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after updation: 
 [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [45]:
# reversing with the help of slicing
a = np.array([3,7,2,6,4,5])
print(a)
print("reverse:\n",a[::-1])

[3 7 2 6 4 5]
reverse:
 [5 4 6 2 7 3]


In [53]:
# using another array 
import numpy as np

array = np.array([1, 2, 3, 4, 5])
# create an empty array with same shape
reversed_array = np.empty_like(array)  

n = len(array)
for i in range(n):
    reversed_array[i] = array[n - 1 - i]

print("Original array:", array)
print("Reversed array:", reversed_array)


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [57]:
# reversing with the help of slicing
a = np.array([3,7,2,6,4,5] , dtype = 'float')
print(a)


[3. 7. 2. 6. 4. 5.]


In [59]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
float_arr = array.astype(float)

print("Original array:", arr)
print("Data type of original array:", arr.dtype)
print("Converted to float array:", float_arr)
print("Data type of float array:", float_arr.dtype)


Original array: [1 2 3 4 5]
Data type of original array: int32
Converted to float array: [1. 2. 3. 4. 5.]
Data type of float array: float64


# --------------------------DONE-----------------------------------