# Assignment 9

In [20]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

a_reshaped = a.reshape(1, -1)
print(a_reshaped)
print('\n')
combined = np.concatenate((a_reshaped, b), axis=0)
print(combined)

[[1 2 3]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# using reshape
b = np.array([[4, 5, 6], [7, 8, 9]])
print(b.reshape(-1))

[4 5 6 7 8 9]


In [26]:
# using ravel()
b = np.array([[4, 5, 6], [7, 8, 9]])
print(b.ravel())

[4 5 6 7 8 9]


In [32]:
# using flip()
b = np.array([[4, 5, 6], [7, 8, 9]])
rev =np.flip(b)
print(rev)

[[9 8 7]
 [6 5 4]]


In [42]:
# using slicing
b = np.array([[4, 5, 6], [7, 8, 9]])
print(b[::-1,::-1])

[[9 8 7]
 [6 5 4]]


In [44]:
# get the maximum value from given array
b = np.array([[42, 25, 65], [17, 18, 49]])
print(np.max(b))

65


In [46]:
# get the minimum value from given array
b = np.array([[42, 25, 65], [17, 18, 49]])
print(np.min(b))

17


In [48]:
# find the no of rows and column of a given array using numpy
b = np.array([[42, 25, 65], [17, 18, 49]])
print(b.shape)

(2, 3)


In [50]:
# Select the element from a given array (each element and specific element)
#using for loop
b = np.array([[42, 25, 65], [17, 18, 49]])
for row in b:
    for e in row:
        print(e)

42
25
65
17
18
49


In [52]:
#using nditer() function
b = np.array([[42, 25, 65], [17, 18, 49]])
for e in np.nditer(b):
    print(e)

42
25
65
17
18
49


In [54]:
# find sum of values in a 2D array using for loop
b = np.array([[42, 25, 65], [17, 18, 49]])
sum = 0
for e in np.nditer(b):
    sum+=e

print("sum=",sum)

sum= 216


In [60]:
# adding , subtarcting, multiplying , dividing  arrays in numpy
a = np.array([[67, 12, 89], [27, 23, 28]])
b = np.array([[42, 25, 65], [17, 18, 49]])
print("addition=\n",a+b)
print("subtraction=\n",a-b)
print("multiplication=\n",a*b)
print("division=\n",a/b)

addition=
 [[109  37 154]
 [ 44  41  77]]
subtraction=
 [[ 25 -13  24]
 [ 10   5 -21]]
multiplication=
 [[2814  300 5785]
 [ 459  414 1372]]
division=
 [[1.5952381  0.48       1.36923077]
 [1.58823529 1.27777778 0.57142857]]


# ---------------------DONE-----------------------------